name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          repository: rahvad/Rahul-Vaddi-Space # Replace with your private repo name
          token: ${{ secrets.GH_TOKEN }}  # GitHub's token for authentication

      - name: Checkout public repository
        uses: actions/checkout@v3
        with:
          repository: rahvad.github.io  # Replace with your public repository's name
          token: ${{ secrets.GH_TOKEN }}  # GitHub token for pushing to the public repo

      - name: Copy files to the public repository
        run: |
          # Remove all existing files in the public repository folder (gh-pages branch)
          rm -rf *

          cp -r * .  # Copy all files and directories

      - name: Commit and push changes
        run: |
          git config user.name "rahvad"
          git config user.email "rahvad@gmail.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main  # Push changes to the public repository
